### ISSUE TITLE
01-rag-concepts notebooks fail on fresh accounts: legacy Claude 3 models, foundation-model ARNs, hardcoded author S3 bucket, and RAGAS stack incompatible with current Python/pyarrow

### ISSUE THREAD

**Issue by jeve7** [aws-samples/rag-workshop-amazon-bedrock-knowledge-bases#12]
## Title
01-rag-concepts notebooks fail on fresh accounts: legacy Claude 3 models, foundation-model ARNs, hardcoded author S3 bucket, and RAGAS stack incompatible with current Python/pyarrow

## Summary
Running all five `01-rag-concepts` notebooks on a fresh account (September 2026) surfaced three independent problems:

1. **Model access** – Notebooks 01–05 hardcode Claude 3 Sonnet/Haiku, which Anthropic now marks as Legacy. Accounts without recent usage of those models get a hard `ValidationException`. Replacement models require inference-profile ARNs and a sampling-parameter fix.
2. **Hardcoded author bucket** – Notebook 05's DLA ingest config points at an S3 bucket from the author's environment, inaccessible from any other account.
3. **Evaluation stack** – Notebook 04's RAGAS section cannot run: the pinned `datasets == 2.14.0` is incompatible with current `pyarrow`, and newer `datasets` releases break on Python 3.14.

All five notebooks were verified working after the fixes below, except notebook 04's evaluation section (blocked by issue 3, an environment problem with no notebook-level fix).

## Environment
- Python 3.14.7 (Homebrew, macOS), pyarrow 25.0.1
- `requirements.txt` as shipped (`datasets == 2.14.0`, `ragas == 0.1.9`, `langchain == 0.3.17`)
- Region: us-east-1

---

### Error
```
ValidationException: An error occurred (ValidationException) when calling the RetrieveAndGenerate operation:
Access denied. This Model is marked by provider as Legacy and you have not been actively using the model
in the last 30 days. Please upgrade to an active model on Amazon Bedrock
```

### Affected references
| Notebook | Location | Model |
|---|---|---|
| `01_create_ingest_documents_test_kb_multi_ds.ipynb` | setup cell | `anthropic.claude-3-sonnet-20240229-v1:0` |
| `01_create_ingest_documents_test_kb_multi_ds.ipynb` | RetrieveAndGenerate cell | `anthropic.claude-3-haiku-20240307-v1:0` |
| `02_managed_retreiveandgenerate_and_streamapi.ipynb` | cell 7 (`model_id`) | `anthropic.claude-3-haiku-20240307-v1:0` |
| `03_customized_rag_retreive_api_hybrid_search_langchain.ipynb` | cell 20 (`modelId`) | `anthropic.claude-3-haiku-20240307-v1:0` |
| `04_customized_rag_retreive_api_langchain_evaluation_ragas.ipynb` | cell 8 (`llm_for_text_generation`) | `anthropic.claude-3-haiku-20240307-v1:0` |
| `04_customized_rag_retreive_api_langchain_evaluation_ragas.ipynb` | cell 8 (`llm_for_evaluation`) | `anthropic.claude-3-sonnet-20240229-v1:0` |
| `05_document_level_kb_ingestion.ipynb` | RetrieveAndGenerate cell (`foundation_model` + `modelArn`) | `anthropic.claude-3-sonnet-20240229-v1:0` |

Enabling model access in the console does **not** fix this; the gating is provider-side.

### Verified fix
Swapping to current models works, but requires two additional changes because current Claude models are **inference-profile only** (`inferenceTypesSupported = INFERENCE_PROFILE`):

**a) Model IDs**
- Generation: `us.anthropic.claude-haiku-4-5-20251001-v1:0`
- Evaluation judge (notebook 04): `us.anthropic.claude-sonnet-4-5-20250929-v1:0`

**b) ARN format** (notebooks 01, 02, and 05 build the ARN by hand)
```python
# before
"arn:aws:bedrock:{}::foundation-model/{}".format(region, foundation_model)

# after
account_id = sts_client.get_caller_identity()["Account"]
"arn:aws:bedrock:{}:{}:inference-profile/{}".format(region, account_id, foundation_model)
```
Notebooks 03 and 04 pass the model ID directly to `invoke_model` / `ChatBedrock`, so only the ID changes there.

**c) Sampling parameters** (notebook 03, payload cell)
Haiku 4.5 rejects `temperature` and `top_p` together:
```
ValidationException: `temperature` and `top_p` cannot both be specified for this model. Please use only one.
```
Removing `"top_p": 1` from the raw Anthropic payload resolves it.

Verified: `RetrieveAndGenerate`, `RetrieveAndGenerateStream`, `InvokeModel`, and the LangChain flows all work with these changes across notebooks 01–05.

---

## Issue 2: Notebook 05 hardcodes the author's S3 bucket

The DLA ingest configuration (ingest pattern 1) ships with:
```python
document_s3_uri = 's3://semantic-kb-9194117/octank_financial_10K.pdf'
```
That bucket belongs to the sample author's environment. From any other account it returns `AccessDenied`, so the document-level ingestion can never succeed as shipped. Symptom in practice: the ingest call appears to hang (boto3 retry cycle) rather than failing with a clear error.

### Suggested fix
Reference the bucket the workshop itself creates in notebook 01 (which already contains `octank_financial_10K.pdf`), ideally derived at runtime from the KB's data source configuration (`get_data_source` → S3 bucket ARN) rather than hardcoded. Verified working when pointed at the workshop-created bucket.

Related: the cleanup cell near the end of notebook 05 deletes knowledge bases. A warning callout before it would help — running it mid-workshop silently breaks notebooks 02–04, which depend on the stored `kb_id`.

---

### Error (as shipped, `datasets == 2.14.0`)
```
AttributeError: module 'pyarrow' has no attribute 'PyExtensionType'
```
`pa.PyExtensionType` was removed in pyarrow 18+. `datasets` 2.14.0 uses it at import time, so `from datasets import Dataset` fails immediately.

### Error (after upgrading `datasets` to 5.0.1)
Imports succeed, but `Dataset.from_dict(...)` fails:
```
TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'
```
Python 3.14 changed the internal `pickle._Pickler._batch_setitems` signature; `datasets`' custom dill pickler has not caught up.

### Root cause
The pinned eval stack (`datasets` 2.14.0 + `ragas` 0.1.9) predates both current pyarrow and Python 3.14. No `datasets` version satisfies both constraints on Python 3.14.

### Suggested fixes (any one unblocks the notebook)
1. **Document a supported Python version** (3.11 or 3.12) in the README; the pinned stack works as-is there.
2. **Drop `datasets` entirely** — it only wraps four lists for RAGAS; current RAGAS accepts plain dicts / its own `EvaluationDataset`, and pandas is already a dependency.
3. **Bump `ragas` off 0.1.9** — 0.2+ has a redesigned API (metric classes, `evaluate()` signature, LLM/embeddings wrappers), so the notebook's imports and `evaluate()` call need updating alongside it.
4. Alternatively, use **Amazon Bedrock's native RAG evaluation** to stay in-platform and drop the third-party eval dependency.

### Minor
`requirements.txt` lists `ragas` twice (unpinned and `== 0.1.9`); worth consolidating.

---

## Checklist for maintainers
- [ ] Replace Claude 3 model IDs across `01-rag-concepts` (check other workshop folders too; not tested here)
- [ ] Switch hand-built `foundation-model` ARNs to `inference-profile` ARNs (notebooks 01, 02, 05)
- [ ] Remove `top_p` from raw Anthropic payloads where `temperature` is also set (notebook 03)
- [ ] Replace the hardcoded `semantic-kb-*` bucket in notebook 05 with the workshop-created bucket / derive from data source config
- [ ] Add a warning before notebook 05's KB-deletion cleanup cell
- [ ] Update the markdown prerequisite notes listing required model access
- [ ] Pin/document a supported Python version or modernize the `datasets`/`ragas` stack (notebook 04)
- [ ] Deduplicate `requirements.txt`
